"""add quiz system tables

Revision ID: 0c03882c8f4d
Revises: d7e130b21718
Create Date: 2026-04-06 17:10:07.337815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c03882c8f4d'
down_revision: Union[str, Sequence[str], None] = 'd7e130b21718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_id'), ['id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_id'), ['id'], unique=False)

    op.create_table('quiz_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_submissions_id'), ['id'], unique=False)

    op.create_table('instructor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['quiz_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructor_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructor_notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructor_notes_id'))

    op.drop_table('instructor_notes')
    with op.batch_alter_table('quiz_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_submissions_id'))

    op.drop_table('quiz_submissions')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_id'))

    op.drop_table('quizzes')
    # ### end Alembic commands ###
