"""update_patinet_and_session_model

Revision ID: 4294962178ac
Revises: 79a4215735e5
Create Date: 2026-03-13 23:32:47.740812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4294962178ac'
down_revision: Union[str, Sequence[str], None] = '79a4215735e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_sessions_patient_id'), ['patient_id'])
        batch_op.create_foreign_key(batch_op.f('fk_sessions_patient_id_patients'), 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_patients_session_id', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('uq_patients_session_id', ['session_id'])
    # ### end Alembic commands ###
