"""Add user management tables

Revision ID: 45d7a8273cca
Revises: g7b8c9d0e1f2
Create Date: 2026-04-05 19:52:14.371840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d7a8273cca'
down_revision: Union[str, Sequence[str], None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_universities_id'), ['id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'UNIVERSITY_ADMIN', 'LAB_ADMIN', 'STUDENT', name='userroleenum'), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('audiogram_points', schema=None) as batch_op:
        batch_op.alter_column('test_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REAL', 'SYNTHETIC', name='patientsourceenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'REAL'"))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_sessions_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_user_id_users', type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.Enum('REAL', 'SYNTHETIC', name='patientsourceenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'REAL'"))

    with op.batch_alter_table('audiogram_points', schema=None) as batch_op:
        batch_op.alter_column('test_type',
               existing_type=sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_id'))
        batch_op.drop_index(batch_op.f('ix_universities_domain'))

    op.drop_table('universities')
    # ### end Alembic commands ###
