"""Initial baseline

Revision ID: 7480bff37abc
Revises:
Create Date: 2026-04-05 14:06:35.767954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7480bff37abc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('REAL', 'SYNTHETIC', name='patientsourceenum'), nullable=False),
    sa.Column('image_ref', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_universities_id'), ['id'], unique=False)

    op.create_table('ears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('hearing_type', sa.Enum('NORMAL', 'CONDUCTIVE', 'SENSORINEURAL', 'MIXED', name='hearingtypeenum'), nullable=True),
    sa.Column('hearing_profile', sa.JSON(), nullable=True),
    sa.Column('hearing_tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'side', name='uq_ears_patient_side')
    )
    with op.batch_alter_table('ears', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ears_id'), ['id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'UNIVERSITY_ADMIN', 'LAB_ADMIN', 'STUDENT', name='userroleenum'), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audiogram_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ear_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('threshold_db', sa.Float(), nullable=False),
    sa.Column('is_no_response', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ear_id'], ['ears.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ear_id', 'test_type', 'frequency', name='uq_points_ear_test_freq')
    )
    with op.batch_alter_table('audiogram_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiogram_points_id'), ['id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ear_side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('masking_level_db', sa.Float(), nullable=True),
    sa.Column('response', sa.Enum('HEARD', 'NOT_HEARD', name='responseenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_id'), ['id'], unique=False)

    op.create_table('final_interpretations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ear_side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('overall_type', sa.Enum('NORMAL', 'CONDUCTIVE', 'SENSORINEURAL', 'MIXED', name='hearingtypeenum'), nullable=True),
    sa.Column('severity', sa.Enum('NORMAL', 'MILD', 'MODERATE', 'MODERATELY_SEVERE', 'SEVERE', 'PROFOUND', 'UNDETERMINED', name='hearingseverityenum'), nullable=True),
    sa.Column('configuration', sa.Enum('ALL_FREQUENCIES', 'LOW_FREQUENCIES', 'MID_FREQUENCIES', 'HIGH_FREQUENCIES', 'SINGLE_FREQUENCY', 'NOTCH_PATTERN', 'OTHER', 'UNDETERMINED', name='hearingdistributionenum'), nullable=True),
    sa.Column('affected_frequencies_hz', sa.JSON(), nullable=False),
    sa.Column('clinical_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ear_side', name='uq_final_interpretation_session_ear')
    )
    with op.batch_alter_table('final_interpretations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_interpretations_id'), ['id'], unique=False)

    op.create_table('stored_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('ear_side', sa.Enum('LEFT', 'RIGHT', name='earsideenum'), nullable=False),
    sa.Column('test_type', sa.Enum('AC', 'AC_MASKED', 'BC', 'BC_MASKED', name='testtypeenum'), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('threshold_db', sa.Float(), nullable=False),
    sa.Column('is_no_response', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stored_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_thresholds_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stored_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_thresholds_id'))

    op.drop_table('stored_thresholds')
    with op.batch_alter_table('final_interpretations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_interpretations_id'))

    op.drop_table('final_interpretations')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('audiogram_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiogram_points_id'))

    op.drop_table('audiogram_points')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('ears', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ears_id'))

    op.drop_table('ears')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_id'))
        batch_op.drop_index(batch_op.f('ix_universities_domain'))

    op.drop_table('universities')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    # ### end Alembic commands ###
