"""remove_university_domain_column

Revision ID: d7e130b21718
Revises: 45d7a8273cca
Create Date: 2026-04-06 11:47:31.136333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e130b21718'
down_revision: Union[str, Sequence[str], None] = '45d7a8273cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_domain'))
        batch_op.drop_column('domain')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_universities_domain'), ['domain'], unique=1)

    # ### end Alembic commands ###
