"""add quiz types and session link

Revision ID: f4e77bc184cd
Revises: 0c03882c8f4d
Create Date: 2026-04-06 19:27:11.318990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e77bc184cd'
down_revision: Union[str, Sequence[str], None] = '0c03882c8f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('answers',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_quiz_submissions_session_id', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.Enum('REGULAR', 'SIMULATOR', name='quiztypeenum'), nullable=False, server_default='REGULAR'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')

    with op.batch_alter_table('quiz_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_submissions_session_id', type_='foreignkey')
        batch_op.alter_column('answers',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
